INSERT INTO labels (name, slug, label_tier, genres, based_in, info_url) VALUES
  ('83', '83', 'emerging', '{UKG}', 'Spain', 'https://en83music.com/'),
  ('696', '696', 'emerging', '{House}', 'UK', 'https://www.instagram.com/696recs/'),
  ('23rdcenturydgtl', '23rdcenturydgtl', 'emerging', '{Techno}', 'UK', 'https://23rdcentury.tech/'),
  ('240 KM/H', '240-kmh', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/240kmhk'),
  ('240 MPH', '240-mph', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/240mphk'),
  ('4 To The Floor', '4-to-the-floor', 'emerging', '{House}', 'UK', 'https://soundcloud.com/4_to_the_floor'),
  ('"44 Label Group', '44-label-group', 'emerging', '{}', NULL, NULL),
  ('Kobosil', 'kobosil', 'emerging', '{Germany}', 'https://44labelgroup.com/en-us/pages/music', NULL),
  ('88 Butterfly', '88-butterfly', 'emerging', '{Deep}', 'Greece', 'https://soundcloud.com/88butterfly-ofc'),
  ('Afterlife', 'afterlife', 'institution', '{Melodic + Progressive}', 'Germany', 'https://www.after.life/'),
  ('AKRONYM', 'akronym', 'emerging', '{Techno}', 'Germany', 'https://www.akronymcollective.com/'),
  ('AKTIVV', 'aktivv', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/aktivv}', NULL, NULL),
  ('Alaula', 'alaula', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/user-86323611'),
  ('All Night Long', 'all-night-long', 'emerging', '{House + Techno}', 'France', 'https://www.allnightlong.com/'),
  ('All We Have Is Now', 'all-we-have-is-now', 'emerging', '{House + Techno}', 'UK', 'https://allwehaveisnow.co.uk/'),
  ('Alula Tunes', 'alula-tunes', 'emerging', '{Melodic + Progressive}', 'Germany', 'http://www.alula-tunes.com/'),
  ('ALWARDA', 'alwarda', 'emerging', '{Techno}', 'Switzerland', 'https://soundcloud.com/alwardarecords'),
  ('Alzaya', 'alzaya', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.alzaya.com/}', NULL, NULL),
  ('Andhera', 'andhera', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/andherarecords'),
  ('ANIITIME', 'aniitime', 'emerging', '{Melodic + Progressive}', 'UK', 'https://www.instagram.com/aniitime/'),
  ('Animarum Black', 'animarum-black', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/animarumrec'),
  ('Animarum Progressive', 'animarum-progressive', 'emerging', '{Trance}', 'Germany', 'https://soundcloud.com/animarumrec'),
  ('Animarum Recordings', 'animarum-recordings', 'emerging', '{Melodic + Progressive}', 'Germany', 'https://soundcloud.com/animarumrec'),
  ('Anjunabeats', 'anjunabeats', 'emerging', '{Trance}', 'UK', 'https://anjunabeats.com/'),
  ('Anjunadeep', 'anjunadeep', 'emerging', '{Deep}', 'UK', 'https://anjunadeep.com/eu'),
  ('Anjunadeep Explorations', 'anjunadeep-explorations', 'emerging', '{Deep}', 'UK', 'https://soundcloud.com/explorations-label'),
  ('Aparenzza Music', 'aparenzza-music', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://aparenzzamusic.com/}', NULL, NULL),
  ('Apogee', 'apogee', 'emerging', '{Techno}', 'UK', 'https://linktr.ee/apogeemusic'),
  ('Arcane', 'arcane', 'emerging', '{Techno}', 'UK', 'https://www.arcanemusic.co.uk/'),
  ('Area Verde', 'area-verde', 'emerging', '{Melodic + Progressive}', 'Spain', 'https://soundcloud.com/areaverde'),
  ('Arkade', 'arkade', 'emerging', '{House}', 'USA', 'https://soundcloud.com/arkade'),
  ('Armada', 'armada', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.armadamusic.com/}', NULL, NULL),
  ('ARTCORE', 'artcore', 'emerging', '{Techno}', 'Spain', 'https://indirapaganotto.com/artcore/label/'),
  ('Astral Records', 'astral-records', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://soundcloud.com/astralrecofc}', NULL, NULL),
  ('Asylum Recordings', 'asylum-recordings', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/asylum-recordings-666}', NULL, NULL),
  ('ATLANT', 'atlant', 'emerging', '{Melodic + Progressive}', 'France', 'https://weareatlant.com/'),
  ('ATW Records', 'atw-records', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/atwrec}', NULL, NULL),
  ('Autektone', 'autektone', 'emerging', '{Techno}', 'Italy', 'https://www.autektone.com/'),
  ('Automatik', 'automatik', 'emerging', '{House + Techno}', 'UK', 'https://www.henribergmann.com/label'),
  ('Awesome Soundwave', 'awesome-soundwave', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.awesomesoundwave.com/}', NULL, NULL),
  ('Axis Records', 'axis-records', 'emerging', '{Techno}', 'USA', 'https://www.axisrecords.com/'),
  ('Azzur Music', 'azzur-music', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://azzur-music.com/}', NULL, NULL),
  ('Backhaus Records', 'backhaus-records', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/bkhskllktv'),
  ('BAD ARM RECORDS', 'bad-arm-records', 'emerging', '{Techno}', 'UK', 'https://badarmrecords.bandcamp.com/'),
  ('Banca De Cá', 'banca-de-c', 'emerging', '{Minimal}', 'Brazil', 'https://soundcloud.com/banca-de-ca'),
  ('BCCO', 'bcco', 'emerging', '{Techno}', 'Germany', 'https://www.bccoberlin.com/'),
  ('Be Free Recordings', 'be-free-recordings', 'emerging', '{Deep}', 'Italy', 'https://soundcloud.com/befreerecordings'),
  ('Be Yourself Music', 'be-yourself-music', 'emerging', '{}', NULL, NULL),
  ('House + Techno', 'house-techno', 'emerging', '{https://beyourselfmusic.com/}', NULL, NULL),
  ('Beat Etruria', 'beat-etruria', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/etruriabeat'),
  ('Beatfreak Recordings', 'beatfreak-recordings', 'emerging', '{Techno}', 'Spain', 'https://beatfreakgroup.com/'),
  ('Big Love', 'big-love', 'emerging', '{House}', 'UK', 'https://soundcloud.com/big-love-recs'),
  ('BITE', 'bite', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/bitelabel'),
  ('blaah! Raw', 'blaah-raw', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/blaahraw}', NULL, NULL),
  ('Black Book Records', 'black-book-records', 'emerging', '{House}', 'USA', 'https://www.blackbookrecs.com/'),
  ('Blackartel Records', 'blackartel-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://www.blackartelrec.com/}', NULL, NULL),
  ('Blackworks', 'blackworks', 'emerging', '{Techno}', 'Spain', 'https://blackworks.es/'),
  ('BLOK', 'blok', 'emerging', '{Techno}', 'Poland', 'https://www.vegablok.com/'),
  ('Blue Dollar Billz', 'blue-dollar-billz', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/bluedollarbillz'),
  ('Boogeyman', 'boogeyman', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/user-76050053'),
  ('BOX RED', 'box-red', 'emerging', '{Minimal}', 'UK', 'https://soundcloud.com/box-red-label'),
  ('BPitch', 'bpitch', 'emerging', '{Techno}', 'Germany', 'https://www.bpitch.de/en/'),
  ('Braslive', 'braslive', 'emerging', '{House}', 'Brazil', 'https://soundcloud.com/braslive'),
  ('Brea Label', 'brea-label', 'emerging', '{Minimal}', 'Argentina', 'https://soundcloud.com/brealabel'),
  ('Bumpin Underground', 'bumpin-underground', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/user-601882831'),
  ('Captive Soul', 'captive-soul', 'emerging', '{Melodic + Progressive}', 'Ukraine', 'https://soundcloud.com/captive-soul-739101056'),
  ('Catch & Release', 'catch-release', 'emerging', '{House}', 'USA', 'https://soundcloud.com/catchandreleaserecords'),
  ('CEP Records', 'cep-records', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/cep-records'),
  ('Cercle', 'cercle', 'emerging', '{House + Techno}', 'France', 'https://www.cercle.io/'),
  ('Chaste Records', 'chaste-records', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/chaste_records'),
  ('Chinotto Records', 'chinotto-records', 'emerging', '{House}', 'Germany', 'https://soundcloud.com/chinotto-records'),
  ('Circa Trax', 'circa-trax', 'emerging', '{}', NULL, NULL),
  ('House + Techno', 'house-techno', 'emerging', '{https://www.circatrax.com/}', NULL, NULL),
  ('CircoLoco', 'circoloco', 'emerging', '{House + Techno}', 'Spain', 'https://circolocorecords.com/'),
  ('Circus Recordings', 'circus-recordings', 'emerging', '{House + Techno}', 'UK', 'https://circusrecordings.com/'),
  ('Classic Music Company', 'classic-music-company', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/classic-music-company}', NULL, NULL),
  ('CLU RECS', 'clu-recs', 'emerging', '{Minimal}', 'France', 'https://soundcloud.com/clurecs'),
  ('Club Heart Broken', 'club-heart-broken', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://clubheartbroken.com/}', NULL, NULL),
  ('CLUB SP33D', 'club-sp33d', 'emerging', '{Techno}', 'Peru', 'https://soundcloud.com/clubsp33d'),
  ('Club Sweat', 'club-sweat', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://sweatitoutmusic.com/club-sweat/}', NULL, NULL),
  ('coco', 'coco', 'emerging', '{Minimal}', 'UK', 'https://soundcloud.com/cocobeatsuk'),
  ('Cocoa', 'cocoa', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/cocoamusiclabel'),
  ('Cocoon Recordings', 'cocoon-recordings', 'emerging', '{Techno}', 'Germany', 'https://www.cocoon.net/'),
  ('COLAPSO', 'colapso', 'emerging', '{Minimal}', 'Brazil', 'https://soundcloud.com/colapsorecs'),
  ('COLOR', 'color', 'emerging', '{Techno}', 'France', 'https://linktr.ee/sparklingwaterboy'),
  ('Comme dans les films', 'comme-dans-les-films', 'emerging', '{Techno}', 'France', 'https://soundcloud.com/commedanslesfilmslabel'),
  ('Confession', 'confession', 'emerging', '{House}', 'France', 'https://www.confessionlabel.com/'),
  ('Constant', 'constant', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/constantsound'),
  ('Cr2 Records', 'cr2-records', 'emerging', '{House}', 'UK', 'https://cr2records.com/'),
  ('Criminal Crisis', 'criminal-crisis', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/criminal_crisis}', NULL, NULL),
  ('Criterio', 'criterio', 'emerging', '{House}', 'Spain', 'https://www.instagram.com/criterio_music/?hl=en'),
  ('Crucast', 'crucast', 'emerging', '{UKG}', 'UK', 'https://www.crucast.com/'),
  ('CUFF', 'cuff', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/thisiscuff}', NULL, NULL),
  ('Cultúra', 'cultra', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://soundcloud.com/cultura_ofc}', NULL, NULL),
  ('Cuttin’ Headz', 'cuttin-headz', 'emerging', '{House}', 'USA', 'https://soundcloud.com/cuttinheadzmusic'),
  ('CXD', 'cxd', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.curieuxdilettanti.com/}', NULL, NULL),
  ('D4D4NCE', 'd4d4nce', 'emerging', '{House}', 'UK', 'https://defected.com/music/releases/label/d4d4nce'),
  ('Dansu Discs', 'dansu-discs', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/dansudiscs'),
  ('Dark Side Of The Sun', 'dark-side-of-the-sun', 'emerging', '{House}', 'Netherlands', 'https://soundcloud.com/darksideofthesunams'),
  ('Dawn Patrol', 'dawn-patrol', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://soundcloud.com/dawnpatrolart}', NULL, NULL),
  ('DCLTD', 'dcltd', 'emerging', '{Techno}', 'Sweden', 'https://soundcloud.com/dcltd'),
  ('Deadline Records', 'deadline-records', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/deadlinerec'),
  ('DEEP WOODS', 'deep-woods', 'emerging', '{Deep}', 'Germany', 'https://prettypink.de/deepwoods/'),
  ('Deeperfect Records', 'deeperfect-records', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/deeperfect-records'),
  ('Defected', 'defected', 'institution', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://defected.com/}', NULL, NULL),
  ('Delicious Recordings', 'delicious-recordings', 'emerging', '{House}', 'Brazil', 'https://www.deliciousrecordings.co/'),
  ('Desert Hearts Records', 'desert-hearts-records', 'emerging', '{House}', 'USA', 'https://deserthearts.us/'),
  ('Desolat', 'desolat', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://desolat.com/}', NULL, NULL),
  ('DFTD', 'dftd', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/dftd}', NULL, NULL),
  ('Digital Glory', 'digital-glory', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/digital-glory?ref=clipboard&p=i&c=1&si=3419DF27A94E48C9931D04341FF0FC0E&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing'),
  ('Dirtybird', 'dirtybird', 'emerging', '{House}', 'USA', 'https://dirtybirdrecords.com/'),
  ('Discoweey', 'discoweey', 'emerging', '{House}', 'Mexico', 'https://soundcloud.com/discoweey'),
  ('Diversions Music', 'diversions-music', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://soundcloud.com/diversions-music}', NULL, NULL),
  ('Diynamic', 'diynamic', 'institution', '{House + Techno}', 'Germany', 'https://www.diynamic.com/'),
  ('DOGGHAÜZ RECORDS', 'dogghauz-records', 'emerging', '{House}', 'Brazil', 'https://soundcloud.com/dogghauzrecords'),
  ('Dolma Records', 'dolma-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/dolma-records}', NULL, NULL),
  ('doof', 'doof', 'emerging', '{Techno}', 'UK', 'https://www.doof-music.com/'),
  ('DopamineWIFI', 'dopaminewifi', 'emerging', '{Trance}', 'France', 'https://soundcloud.com/dopaminewifi'),
  ('dpe', 'dpe', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/dperecords'),
  ('Dr Banana', 'dr-banana', 'emerging', '{UKG}', 'UK', 'https://drbanana.co.uk/'),
  ('Dreaming Forever', 'dreaming-forever', 'emerging', '{House + Techno}', 'UK', 'https://soundcloud.com/dreaming-forever-1360033'),
  ('Drumcode', 'drumcode', 'institution', '{Techno}', 'Sweden', 'https://www.drumcode.se/'),
  ('DSK Records', 'dsk-records', 'emerging', '{Techno}', 'Spain', 'https://dskonnect.com/dskrecords/'),
  ('DVINE Sounds', 'dvine-sounds', 'emerging', '{House}', 'UK', 'https://soundcloud.com/d-vine-sounds'),
  ('Earful of Wax', 'earful-of-wax', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/earfulofwax'),
  ('Eastenderz', 'eastenderz', 'emerging', '{Minimal}', 'UK', 'https://www.eastenderz.com/'),
  ('EB_REX', 'ebrex', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/estellaboersma'),
  ('EC2A', 'ec2a', 'emerging', '{UKG}', 'UK', 'https://www.ec2aworldwide.com/'),
  ('Edible Records', 'edible-records', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.instagram.com/ediblerecords/}', NULL, NULL),
  ('Ei8ht Records', 'ei8ht-records', 'emerging', '{}', NULL, NULL),
  ('House + Techno', 'house-techno', 'emerging', '{https://soundcloud.com/ei8htrecords}', NULL, NULL),
  ('Eleatics Records', 'eleatics-records', 'emerging', '{Melodic + Progressive}', 'Ukraine', 'http://eleaticsrecords.com/'),
  ('Elektra', 'elektra', 'emerging', '{Techno}', 'UK', 'https://elektrasparks.com/'),
  ('Elemento Records', 'elemento-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://elemento-records.com/}', NULL, NULL),
  ('Elrow Music', 'elrow-music', 'emerging', '{House}', 'Spain', 'https://elrow.com/en/music'),
  ('Emperor Recordings', 'emperor-recordings', 'emerging', '{Techno}', 'Serbia', 'https://soundcloud.com/emperor-recordings'),
  ('Encasa Records', 'encasa-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/encasarecords}', NULL, NULL),
  ('ENTWEIHEN', 'entweihen', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/entweihenrecords}', NULL, NULL),
  ('ERRORR', 'errorr', 'emerging', '{Melodic + Progressive}', 'Brazil', 'https://errorrlabel.com/'),
  ('EvilGroove Records', 'evilgroove-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/evilgroove-records}', NULL, NULL),
  ('EXE AUDIO', 'exe-audio', 'emerging', '{House}', 'Bulgaria', 'https://www.execlub.bg/'),
  ('Exhale', 'exhale', 'emerging', '{Techno}', 'Belgium', 'https://www.exhalemusic.net/'),
  ('Experts Only', 'experts-only', 'emerging', '{House}', 'USA', 'https://expertsonlyrecs.com/'),
  ('Extra Energy', 'extra-energy', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/extra-energy'),
  ('Factory 93', 'factory-93', 'emerging', '{Techno}', 'USA', 'https://www.thefactory93.com/records/'),
  ('Faith', 'faith', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.faith.london/}', NULL, NULL),
  ('Fantastic Voyage', 'fantastic-voyage', 'emerging', '{House + Techno}', 'USA', 'https://soundcloud.com/fantasticvoyagemusic'),
  ('Faya Combo', 'faya-combo', 'emerging', '{House}', 'France', 'https://www.traxsource.com/label/28583/faya-combo'),
  ('Fckng Serious', 'fckng-serious', 'emerging', '{Techno}', 'Germany', 'https://www.fckng-serious.de/'),
  ('Filth on Acid', 'filth-on-acid', 'emerging', '{Techno}', 'Netherlands', 'https://soundcloud.com/filthonacid'),
  ('Finder Records', 'finder-records', 'emerging', '{Techno}', 'Ukraine', 'https://soundcloud.com/finder-rec/tracks'),
  ('flat__22', 'flat22', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://www.flat--22.com/}', NULL, NULL),
  ('FLIRT WITH CHAOS', 'flirt-with-chaos', 'emerging', '{Techno}', 'Australia', 'http://www.flirtwithchaos.com/'),
  ('Flying Hearts', 'flying-hearts', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.instagram.com/weare.flyinghearts/}', NULL, NULL),
  ('Forever Days', 'forever-days', 'emerging', '{House}', 'UK', 'https://foreverdays.komi.io/'),
  ('Four40', 'four40', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/four40recordsuk'),
  ('Frau Blau', 'frau-blau', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://soundcloud.com/fraublaumusic}', NULL, NULL),
  ('Freak', 'freak', 'emerging', '{House}', 'UK', 'https://www.instagram.com/freak.label/'),
  ('Freeworld Recordss', 'freeworld-recordss', 'emerging', '{House}', 'UK', 'https://soundcloud.com/freeworld-recordss'),
  ('Freeze Records', 'freeze-records', 'emerging', '{House}', 'USA', 'https://toddterry.com/freeze-records'),
  ('Front Left Recordings', 'front-left-recordings', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/frontleftrecordings'),
  ('Garage Shared', 'garage-shared', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/garageshared'),
  ('GD4YA', 'gd4ya', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/gd4ya}', NULL, NULL),
  ('getbusy', 'getbusy', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/getbusy_rec'),
  ('Gimme a Break Records', 'gimme-a-break-records', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/gimmeabreakrecords}', NULL, NULL),
  ('GLBDOM Classic', 'glbdom-classic', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/glbdom_classic'),
  ('Glitterbox', 'glitterbox', 'emerging', '{House}', 'UK', 'https://glitterboxibiza.com/'),
  ('Gomboc Records', 'gomboc-records', 'emerging', '{Techno}', 'Argentina', 'https://soundcloud.com/gombocrec'),
  ('Gorin Recordings', 'gorin-recordings', 'emerging', '{House}', 'Japan', 'http://gorinrecordings.com/'),
  ('Gritty Records', 'gritty-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/gritty_music}', NULL, NULL),
  ('Groove Estate Records', 'groove-estate-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/grooveestaterecords}', NULL, NULL),
  ('Groove Street Berlin', 'groove-street-berlin', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/groove030'),
  ('Gudu', 'gudu', 'respected', '{House}', 'Germany', 'https://peggygou.com/gudu-records'),
  ('Habitat', 'habitat', 'emerging', '{Melodic + Progressive}', 'UK', 'https://www.habitat.art/'),
  ('Haku', 'haku', 'emerging', '{Techno}', 'France', 'https://www.instagram.com/hakubycara/'),
  ('Happy Techno', 'happy-techno', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/happytechnomusic'),
  ('Hardline', 'hardline', 'emerging', '{UKG}', 'UK', 'https://hardline.world/'),
  ('hau5trap', 'hau5trap', 'emerging', '{House}', 'USA', 'https://www.hau5trap.com/'),
  ('Heavy House Society', 'heavy-house-society', 'emerging', '{Minimal}', 'Portugal', 'https://soundcloud.com/heavyhousesociety'),
  ('hedZup records', 'hedzup-records', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://hedzupmusic.com/}', NULL, NULL),
  ('HEISSS Berlin', 'heisss-berlin', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://heisssberlin.com/}', NULL, NULL),
  ('Hekate', 'hekate', 'respected', '{Techno}', 'Netherlands', 'https://soundcloud.com/hekaterecords'),
  ('Heldeep', 'heldeep', 'emerging', '{House}', 'Netherlands', 'https://heldeeprecords.com/'),
  ('Hellbent', 'hellbent', 'emerging', '{House}', 'USA', 'https://hellbentrecs.com/'),
  ('Here&There', 'herethere', 'emerging', '{House}', 'USA', 'https://soundcloud.com/hereandtherecreates'),
  ('Higher Ground', 'higher-ground', 'emerging', '{House}', 'USA', 'https://higherground.house/'),
  ('HILOMATIK', 'hilomatik', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/hilomatik}', NULL, NULL),
  ('Hood Politics', 'hood-politics', 'emerging', '{House}', 'USA', 'https://soundcloud.com/hoodpoliticsrecords'),
  ('Hot Creations', 'hot-creations', 'institution', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://hotcreations.com/}', NULL, NULL),
  ('Hot Fuss', 'hot-fuss', 'emerging', '{House}', 'Belgium', 'https://www.hot-fuss.com/'),
  ('Hot Meal Records', 'hot-meal-records', 'emerging', '{House + Techno}', 'Germany', 'https://soundcloud.com/hotmealrecs'),
  ('HOTTRAX', 'hottrax', 'emerging', '{House}', 'UK', 'https://soundcloud.com/hottraxmusic'),
  ('Houbless Music', 'houbless-music', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/houbless-music}', NULL, NULL),
  ('House of Love', 'house-of-love', 'emerging', '{House}', 'France', 'https://www.houseoflove.net/'),
  ('HOUSIX', 'housix', 'emerging', '{House}', 'Brazil', 'https://soundcloud.com/housixrecords'),
  ('Human After All', 'human-after-all', 'emerging', '{House}', 'Ecuador', 'https://soundcloud.com/humanafterallec'),
  ('Hurry Up Slowly', 'hurry-up-slowly', 'emerging', '{House}', 'USA', 'https://hurryupslowly.io/'),
  ('HypnoVizion', 'hypnovizion', 'emerging', '{Dubstep}', 'USA', 'https://www.hypnovizion.com/'),
  ('Impulsive Behavior', 'impulsive-behavior', 'emerging', '{}', NULL, NULL),
  ('Trance', 'trance', 'emerging', '{https://soundcloud.com/impulsive_behavior}', NULL, NULL),
  ('In 2 Deep', 'in-2-deep', 'emerging', '{House}', 'UK', 'https://www.instagram.com/in2deeprecs/'),
  ('Influence Records', 'influence-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/influenceireland}', NULL, NULL),
  ('INHERIT', 'inherit', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.inherit-records.com/}', NULL, NULL),
  ('INNERGATE Records', 'innergate-records', 'emerging', '{Techno}', 'Georgia', 'https://soundcloud.com/innergatetechno'),
  ('Innervisions', 'innervisions', 'institution', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.innervisions.com/}', NULL, NULL),
  ('Innocent Music', 'innocent-music', 'emerging', '{Minimal}', 'Slovenia', 'https://innocentmusic.si/'),
  ('Insectum Records', 'insectum-records', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/insectumrecords'),
  ('Insomniac Records', 'insomniac-records', 'emerging', '{House}', 'USA', 'https://www.insomniacmusicgroup.com/label/insomniac-records/'),
  ('Intec Digital', 'intec-digital', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/intec-digital}', NULL, NULL),
  ('Interstellar', 'interstellar', 'emerging', '{Melodic + Progressive}', 'USA', 'https://www.insomniacmusicgroup.com/label/interstellar/'),
  ('Intrepid Skin', 'intrepid-skin', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/intrepidskin'),
  ('Inward Records', 'inward-records', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://soundcloud.com/inwardrecords}', NULL, NULL),
  ('"Ismus', 'ismus', 'emerging', '{}', NULL, NULL),
  ('Chalotte de Witte', 'chalotte-de-witte', 'emerging', '{Belgium}', 'https://soundcloud.com/ismusberlin', NULL),
  ('Issues', 'issues', 'emerging', '{House}', 'Greece', 'https://soundcloud.com/issueslabel'),
  ('It''s All In Your Head', 'its-all-in-your-head', 'emerging', '{Melodic + Progressive}', 'France', 'https://soundcloud.com/iaiyh_ofc'),
  ('Itzel', 'itzel', 'emerging', '{Melodic + Progressive}', 'Turkey', 'https://www.itzelrecords.com/'),
  ('Jaguar Records', 'jaguar-records', 'emerging', '{Minimal}', 'Italy', 'https://www.instagram.com/jaguar_records_ofc_/'),
  ('JAM', 'jam', 'emerging', '{Melodic + Progressive}', 'Italy', 'https://sampaganini.com/music/'),
  ('JANUS REKORDZ', 'janus-rekordz', 'emerging', '{Techno}', 'USA', 'https://soundcloud.com/janus-rekordz'),
  ('Joker Black Label', 'joker-black-label', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/joker-black-label?ref=clipboard&p=a&c=0&si=2563ff6306954d11b22a006010a7f294&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing}', NULL, NULL),
  ('Juicy Records', 'juicy-records', 'emerging', '{House}', 'Brazil', 'https://soundcloud.com/juicyrecordsbr'),
  ('"Juicy', 'juicy', 'emerging', '{Robbie Rivera}', 'Minimal', 'UK'),
  ('K N KT', 'k-n-kt', 'emerging', '{Techno}', 'Germany', 'https://jiltanner.de/'),
  ('K4B', 'k4b', 'emerging', '{House}', 'UK', 'https://k4b-records.bandcamp.com/music'),
  ('KAOS', 'kaos', 'emerging', '{Techno}', 'Germany', 'https://www.instagram.com/kaos_oaks_/?hl=en'),
  ('Kapitalist Dance Club', 'kapitalist-dance-club', 'emerging', '{Techno}', 'France', 'https://linktr.ee/kapitalist_dance_club'),
  ('Keinemusik', 'keinemusik', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://keinemusik.com/}', NULL, NULL),
  ('Kitsuné Musique', 'kitsun-musique', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://maisonkitsune.com/mk/kitsune-musique/}', NULL, NULL),
  ('Klaphouse Records', 'klaphouse-records', 'emerging', '{House}', 'Italy', 'https://www.klaphouse.com/'),
  ('Klasse Wrecks', 'klasse-wrecks', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://klassewrecks.com/}', NULL, NULL),
  ('Kluster Records', 'kluster-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/klusterecords}', NULL, NULL),
  ('Knee Deep In Sound', 'knee-deep-in-sound', 'respected', '{House}', 'UK', 'https://www.hotsince82.com/'),
  ('KNOXX', 'knoxx', 'emerging', '{Techno}', 'Canada', 'https://www.instagram.com/knoxxrecords/'),
  ('KNTXT', 'kntxt', 'respected', '{Techno}', 'Belgium', 'https://kntxt.be/'),
  ('Knuck!', 'knuck', 'emerging', '{House}', 'Mexico', 'https://www.traxsource.com/label/53743/knck-ltd'),
  ('Kode Fervo', 'kode-fervo', 'emerging', '{Minimal}', 'Brazil', 'https://soundcloud.com/kodefervo'),
  ('Kontor Records', 'kontor-records', 'emerging', '{House}', 'Germany', 'https://kontorrecords.de/'),
  ('Kormusik', 'kormusik', 'emerging', '{Melodic + Progressive}', 'Italy', 'https://soundcloud.com/kormusik'),
  ('Kraftek', 'kraftek', 'emerging', '{Techno}', 'USA', 'https://kraftekmusic.com/'),
  ('Kurai Records', 'kurai-records', 'emerging', '{Techno}', 'USA', 'https://kurairecords.com/'),
  ('KYSH Records', 'kysh-records', 'emerging', '{Techno}', 'Poland', 'https://soundcloud.com/kyshrecords'),
  ('La Pera Records', 'la-pera-records', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/laperarecords'),
  ('LATE CHECKOUT', 'late-checkout', 'emerging', '{House}', 'UK', 'https://latecheckoutrecords.komi.io/'),
  ('Libero Records', 'libero-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://liberosound.co.uk/}', NULL, NULL),
  ('Life and Death', 'life-and-death', 'emerging', '{House + Techno}', 'Italy', 'https://lifeanddeath.us/'),
  ('Lighthouse Records', 'lighthouse-records', 'emerging', '{House + Techno}', 'France', 'https://soundcloud.com/lighthouselabel'),
  ('Lighthouse Records', 'lighthouse-records', 'emerging', '{Techno}', 'Netherlands', 'https://soundcloud.com/lighthouserecordsams'),
  ('Locked On Records', 'locked-on-records', 'emerging', '{UKG}', 'UK', 'https://lockedonrecordings.co.uk/'),
  ('Lost City Archives', 'lost-city-archives', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/lost-city-archives'),
  ('Love Attack', 'love-attack', 'emerging', '{Deep}', 'UK', 'https://soundcloud.com/loveattackrecords'),
  ('Loving Plague', 'loving-plague', 'emerging', '{House}', 'USA', 'https://soundcloud.com/loving-plague'),
  ('LTF Records', 'ltf-records', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://listentoflow.com/}', NULL, NULL),
  ('Luv & Lust', 'luv-lust', 'emerging', '{House + Techno}', 'USA', 'https://linktr.ee/luvloofy'),
  ('Maccabi House', 'maccabi-house', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://soundcloud.com/maccabihouse}', NULL, NULL),
  ('Mad Decent', 'mad-decent', 'emerging', '{House}', 'USA', 'https://maddecent.com/'),
  ('Madorasindahouse', 'madorasindahouse', 'emerging', '{Deep}', 'Greece', 'http://www.madorasindahouse.com/'),
  ('Mahool Records', 'mahool-records', 'emerging', '{House + Techno}', 'Saudi Arabia', 'https://www.instagram.com/mahoolrecords/'),
  ('Maison Close', 'maison-close', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/maisoncloserecords}', NULL, NULL),
  ('MAISON Label', 'maison-label', 'emerging', '{House}', 'UK', 'https://soundcloud.com/maisonlabel?ref=clipboard&p=i&c=1&si=A944B3078F1A4CDDB9EFDE2BD2655FE0&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing'),
  ('Make The GIrls Dance', 'make-the-girls-dance', 'emerging', '{House}', 'USA', 'https://soundcloud.com/make-the-girls-dance-recs'),
  ('Manus In Mano', 'manus-in-mano', 'emerging', '{Deep}', 'Germany', 'https://www.instagram.com/manusinmanomusic/'),
  ('Más Vida Music', 'ms-vida-music', 'emerging', '{House}', 'UK', 'https://www.masvida.co.uk/'),
  ('Masked Rules', 'masked-rules', 'emerging', '{Techno}', 'Germany', 'https://maskedrules.com/'),
  ('Material Series', 'material-series', 'emerging', '{House}', 'Netherlands', 'https://soundcloud.com/materialseries'),
  ('mau5trap', 'mau5trap', 'emerging', '{Dubstep}', 'USA', 'https://mau5trap.com/'),
  ('Method 808', 'method-808', 'emerging', '{Techno}', 'UK', 'https://soundcloud.com/method_808'),
  ('MicroHertz', 'microhertz', 'emerging', '{Minimal}', 'UK', 'https://soundcloud.com/microhertzmusic'),
  ('Miniline', 'miniline', 'emerging', '{Minimal}', 'Colombia', 'https://www.instagram.com/minilinelabel/'),
  ('Ministry of Sound', 'ministry-of-sound', 'emerging', '{House}', 'UK', 'https://ministryofsound.com/'),
  ('MITSU2000', 'mitsu2000', 'emerging', '{Trance}', 'Germany', 'https://mitsu2000.com/'),
  ('Miura', 'miura', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/miurarecords}', NULL, NULL),
  ('Moan Recordings', 'moan-recordings', 'emerging', '{Minimal}', 'Italy', 'https://www.moanrec.com/'),
  ('Molotov21', 'molotov21', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/molotov21}', NULL, NULL),
  ('Monasterio', 'monasterio', 'emerging', '{Techno}', 'Russia', 'https://monasterio.moscow/'),
  ('Monstercat', 'monstercat', 'emerging', '{}', NULL, NULL),
  ('Dubstep', 'dubstep', 'emerging', '{https://www.monstercat.com/}', NULL, NULL),
  ('Mood Child', 'mood-child', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://moodchild.art/}', NULL, NULL),
  ('Mood Records', 'mood-records', 'emerging', '{Techno}', 'UK', 'https://soundcloud.com/moodrecords'),
  ('Mouseville', 'mouseville', 'emerging', '{Techno}', 'Sweden', 'https://www.ericprydz.com/mouseville'),
  ('Movin’ Records', 'movin-records', 'emerging', '{House}', 'USA', 'https://movinrecords.bandcamp.com/'),
  ('MUDRA', 'mudra', 'emerging', '{House + Techno}', 'Brazil', 'https://soundcloud.com/mudrasound'),
  ('Multinotes', 'multinotes', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://soundcloud.com/multinotes}', NULL, NULL),
  ('MUSE', 'muse', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/muse_records}', NULL, NULL),
  ('Mushroom Smile Records', 'mushroom-smile-records', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/mushroom-smile-records'),
  ('Music is 4 Lovers', 'music-is-4-lovers', 'emerging', '{Minimal}', 'USA', 'https://www.musicis4lovers.com/category/mi4l-label/'),
  ('music is blaah!', 'music-is-blaah', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/musicisblaah}', NULL, NULL),
  ('Music On', 'music-on', 'emerging', '{House}', 'Italy', 'https://musicon.com/'),
  ('Muted Records', 'muted-records', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/muted-records'),
  ('nachtsieger', 'nachtsieger', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/nachtsieger'),
  ('NAIMA', 'naima', 'emerging', '{Minimal}', 'Italy', 'https://soundcloud.com/naima-musica'),
  ('Namata', 'namata', 'emerging', '{Minimal}', 'Brazil', 'https://soundcloud.com/namatarecords'),
  ('NATURE', 'nature', 'emerging', '{House}', 'UK', 'https://www.instagram.com/naturerecords__/'),
  ('NC4K', 'nc4k', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.nc4k.xyz/}', NULL, NULL),
  ('Nervous Records', 'nervous-records', 'emerging', '{House}', 'USA', 'https://nervousnyc.com/'),
  ('New Tab Music', 'new-tab-music', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.newtabmusic.com/}', NULL, NULL),
  ('Night Bass', 'night-bass', 'emerging', '{House}', 'USA', 'https://www.nightbassrecords.com/'),
  ('Night Service Only', 'night-service-only', 'emerging', '{House}', 'USA', 'https://cidmusic.com/night-service-only/'),
  ('Ninja Tune', 'ninja-tune', 'emerging', '{House + Techno}', 'UK', 'https://www.ninjatune.net/home'),
  ('Nitecutz', 'nitecutz', 'emerging', '{House}', 'UK', 'https://soundcloud.com/nitecutz'),
  ('No Context', 'no-context', 'emerging', '{House}', 'UK', 'https://nocontextrecords.com/'),
  ('NoArt', 'noart', 'emerging', '{House}', 'Netherlands', 'https://www.noartmusic.com/'),
  ('North of Neptune', 'north-of-neptune', 'emerging', '{House}', 'USA', 'https://www.repopulatemars.com/north-of-neptune'),
  ('Not So Unknown', 'not-so-unknown', 'emerging', '{Melodic + Progressive}', 'Netherlands', 'https://www.instagram.com/notso.unknown/?hl=en'),
  ('Nothing But...', 'nothing-but', 'emerging', '{Melodic + Progressive}', 'UK', 'http://www.lwrecordings.com/'),
  ('NOWNOW', 'nownow', 'emerging', '{Techno}', 'Netherlands', 'https://soundcloud.com/nownowrecords'),
  ('NSDA', 'nsda', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/nsdarecords'),
  ('Nu Groove', 'nu-groove', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/nu-groove-records}', NULL, NULL),
  ('Nuvolve', 'nuvolve', 'emerging', '{UKG}', 'UK', 'https://nuvolvemusic.com/'),
  ('NVDRZ', 'nvdrz', 'emerging', '{House}', 'Netherlands', 'https://soundcloud.com/nvdrz_music'),
  ('NYX Music', 'nyx-music', 'emerging', '{Deep}', 'UK', 'https://www.instagram.com/wearenyx/'),
  ('NŸX Records', 'nx-records', 'emerging', '{Techno}', 'France', 'https://soundcloud.com/nyx-records'),
  ('Oaken Palace Records', 'oaken-palace-records', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/oaken-palace-records'),
  ('OAKS', 'oaks', 'emerging', '{Techno}', 'Germany', 'https://www.instagram.com/kaos_oaks_/?hl=en'),
  ('Obsess Label', 'obsess-label', 'emerging', '{Techno}', 'USA', 'https://soundcloud.com/obsesslabel'),
  ('Obsessions', 'obsessions', 'emerging', '{House}', 'USA', 'https://soundcloud.com/obsessionsrecords'),
  ('Octopus', 'octopus', 'emerging', '{}', NULL, NULL),
  ('House + Techno', 'house-techno', 'emerging', '{https://www.octopusrecordings.com}', NULL, NULL),
  ('Oddity', 'oddity', 'emerging', '{House + Techno}', 'Spain', 'https://soundcloud.com/oddityrecordings'),
  ('OFF FIRE', 'off-fire', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/offfirelabel'),
  ('OH2', 'oh2', 'emerging', '{Deep}', 'Netherlands', 'https://soundcloud.com/oh2records'),
  ('Ohana Music', 'ohana-music', 'emerging', '{Minimal}', 'Spain', 'https://soundcloud.com/ohanamusic_label'),
  ('Omny Lab', 'omny-lab', 'emerging', '{Techno}', 'France', 'https://soundcloud.com/omnylab'),
  ('One People', 'one-people', 'emerging', '{Deep}', 'UK', 'https://www.musicweek.com/labels/read/defected-launches-afro-house-label-one-people/089259'),
  ('One Records', 'one-records', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/one-records'),
  ('ONE:AM', 'oneam', 'emerging', '{House + Techno}', 'USA', 'https://oneamrecords.com/'),
  ('ONISM', 'onism', 'emerging', '{Melodic + Progressive}', 'Spain', 'https://soundcloud.com/onismusic'),
  ('ONLYTRANCE', 'onlytrance', 'emerging', '{Trance}', 'Germany', 'https://soundcloud.com/onlytr4nce'),
  ('Ophelia Records', 'ophelia-records', 'emerging', '{Dubstep}', 'USA', 'https://opheliarecords.com/'),
  ('ORBITAL', 'orbital', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/orbitalrecords-cosmos'),
  ('Organic Pieces', 'organic-pieces', 'emerging', '{House}', 'Brazil', 'https://soundcloud.com/organicpieces'),
  ('ORGANÏK', 'organk', 'emerging', '{Techno}', 'France', 'https://soundcloud.com/organikparis'),
  ('Orianna Records', 'orianna-records', 'emerging', '{Deep}', 'UK', 'https://www.oriannarecords.com/'),
  ('ORIGINS RCRDS', 'origins-rcrds', 'emerging', '{Minimal}', 'UK', 'https://linktr.ee/joshbutlermusic'),
  ('Ovrdose Records', 'ovrdose-records', 'emerging', '{House}', 'Netherlands', 'https://soundcloud.com/ovrdoseofficial'),
  ('para//e/', 'parae', 'emerging', '{Trance}', 'Germany', 'https://agency-parallel.com/'),
  ('Parrots Records', 'parrots-records', 'emerging', '{Deep}', 'Brazil', 'https://soundcloud.com/parrotsrec'),
  ('Perspectives Digital', 'perspectives-digital', 'emerging', '{Melodic + Progressive}', 'Germany', 'https://soundcloud.com/perspectivesdigital'),
  ('Pink Bag Records', 'pink-bag-records', 'emerging', '{Minimal}', 'USA', 'https://soundcloud.com/pinkbagrecords'),
  ('PIV', 'piv', 'emerging', '{House}', 'Netherlands', 'https://pivrecords.com/'),
  ('Plastik People Recordings', 'plastik-people-recordings', 'emerging', '{UKG}', 'USA', 'https://soundcloud.com/plastikpeoplerecordings'),
  ('PoleGroup', 'polegroup', 'emerging', '{Techno}', 'Spain', 'https://polegroup.net/index.php'),
  ('polyamor', 'polyamor', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://polyamorberlin.com/}', NULL, NULL),
  ('Primitive UK', 'primitive-uk', 'emerging', '{UKG}', 'UK', 'https://primitivemusicuk.com/'),
  ('Propa Records', 'propa-records', 'emerging', '{UKG}', 'UK', 'https://www.instagram.com/proparecords/'),
  ('Pryda Recordings', 'pryda-recordings', 'emerging', '{House}', 'Sweden', 'https://www.ericprydz.com/pryda'),
  ('Psicodelica', 'psicodelica', 'emerging', '{Deep}', 'Colombia', 'https://soundcloud.com/psicodelicalabel'),
  ('PULZAR', 'pulzar', 'emerging', '{Trance}', 'Germany', 'https://soundcloud.com/p-u-l-z-a-r'),
  ('Puzzles Records', 'puzzles-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.puzzlesrecords.com/}', NULL, NULL),
  ('qp', 'qp', 'emerging', '{}', NULL, NULL),
  ('Trance', 'trance', 'emerging', '{https://soundcloud.com/qpgermany}', NULL, NULL),
  ('Radikon', 'radikon', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://radikon-label.com/}', NULL, NULL),
  ('range.', 'range', 'emerging', '{Minimal}', 'USA', 'https://www.rangertrucco.com/'),
  ('Rave Culture', 'rave-culture', 'emerging', '{Techno}', 'USA', 'https://soundcloud.com/rave-culture-records?ref=clipboard&p=i&c=1&si=A2F57954BF7543F582AE393C2F641F35&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing'),
  ('RAW', 'raw', 'emerging', '{Techno}', 'France', 'https://www.raw-people.com/'),
  ('Rawsome Deep', 'rawsome-deep', 'emerging', '{Deep}', 'USA', 'https://soundcloud.com/rawsomerecords'),
  ('Rawsome Recordings', 'rawsome-recordings', 'emerging', '{House}', 'USA', 'https://soundcloud.com/rawsomerecords'),
  ('Rawtracks Label', 'rawtracks-label', 'emerging', '{Minimal}', 'Spain', 'https://soundcloud.com/rawtracks_label'),
  ('REALM', 'realm', 'emerging', '{House + Techno}', 'UK', 'https://www.realm-records.com/'),
  ('REBOOT', 'reboot', 'emerging', '{Techno}', 'Ireland', 'https://rebootevents.ie/'),
  ('RECKLESS Records', 'reckless-records', 'emerging', '{Techno}', 'Netherlands', 'https://reckless-rec.com/'),
  ('Redefy Records', 'redefy-records', 'emerging', '{House}', 'UK', 'https://soundcloud.com/redefyrecords'),
  ('Redimension', 'redimension', 'emerging', '{House + Techno}', 'Italy', 'https://www.redimensionmusic.com/'),
  ('Redline Records', 'redline-records', 'emerging', '{UKG}', 'New Zealand', 'https://soundcloud.com/redlinerecords03'),
  ('Reecords', 'reecords', 'emerging', '{Minimal}', 'Spain', 'https://soundcloud.com/reecordsabel'),
  ('Relative Music', 'relative-music', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/user-240085360}', NULL, NULL),
  ('RENEGADE METHODZ', 'renegade-methodz', 'emerging', '{Techno}', 'Greece', 'https://soundcloud.com/endlec'),
  ('Repopulate Mars', 'repopulate-mars', 'emerging', '{House}', 'USA', 'https://www.repopulatemars.com/'),
  ('Reptile Mob', 'reptile-mob', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/reptile-mob'),
  ('Retail Records', 'retail-records', 'emerging', '{House}', 'USA', 'https://soundcloud.com/Retail-Records'),
  ('Revised Records', 'revised-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/revisedrecords}', NULL, NULL),
  ('Revival New York', 'revival-new-york', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.revival-ny.com/}', NULL, NULL),
  ('Revolution Records', 'revolution-records', 'emerging', '{Techno}', 'UK', 'https://linktr.ee/RevolutionRecs'),
  ('Rhythm Werk', 'rhythm-werk', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/rhythmwerk'),
  ('RINSE+REPEAT', 'rinserepeat', 'emerging', '{House}', 'USA', 'https://www.goodbetmusic.com/'),
  ('Ritual', 'ritual', 'emerging', '{House + Techno}', 'France', 'https://soundcloud.com/ritualofc'),
  ('Rose Avenue', 'rose-avenue', 'emerging', '{Melodic + Progressive}', 'USA', 'https://www.roseavenuerecs.com/'),
  ('Roush Label', 'roush-label', 'emerging', '{Minimal}', 'Spain', 'https://www.roushlabel.com/'),
  ('Rugburn', 'rugburn', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/rugburnlabel}', NULL, NULL),
  ('Running Clouds', 'running-clouds', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.running-clouds.com/}', NULL, NULL),
  ('Saike', 'saike', 'emerging', '{Techno}', 'France', 'https://soundcloud.com/saikelabel'),
  ('SASS', 'sass', 'emerging', '{House + Techno}', 'France', 'https://www.instagram.com/sasslabel/?hl=en'),
  ('Say What? Recordings', 'say-what-recordings', 'emerging', '{Techno}', 'Belgium', 'https://soundcloud.com/saywhatrecords'),
  ('Second State', 'second-state', 'emerging', '{Techno}', 'Germany', 'https://secondstate.fanlink.tv/Hello/demo'),
  ('selected berlin', 'selected-berlin', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/selected-berlin}', NULL, NULL),
  ('Selected Records', 'selected-records', 'emerging', '{Techno}', 'Spain', 'https://selectedrecords.bandcamp.com/'),
  ('selected.', 'selected', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://selectedbase.com/}', NULL, NULL),
  ('Senso Sounds', 'senso-sounds', 'emerging', '{House + Techno}', 'Germany', 'https://www.senso-sounds.net/'),
  ('sequence music', 'sequence-music', 'emerging', '{Melodic + Progressive}', 'UK', 'https://soundcloud.com/sequencesheffield'),
  ('SESH', 'sesh', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/seshdawgsunited}', NULL, NULL),
  ('Seven Dials Records', 'seven-dials-records', 'emerging', '{Minimal}', 'UK', 'https://soundcloud.com/sevendialsrecords'),
  ('Sexyrecs', 'sexyrecs', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/sexyrecs'),
  ('Shadow City', 'shadow-city', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/shadow-city}', NULL, NULL),
  ('Shall Not Fade', 'shall-not-fade', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/shallnotfade'),
  ('SHÈN', 'shn', 'emerging', '{House + Techno}', 'UK', 'https://bio.to/SHENpresents'),
  ('SHK', 'shk', 'emerging', '{Minimal}', 'UK', 'https://www.instagram.com/shklabel/'),
  ('Short Circuit', 'short-circuit', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/short-circuit-bk}', NULL, NULL),
  ('Shuffle ''n'' Swing', 'shuffle-n-swing', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/shuffle-n-swing'),
  ('Siamese', 'siamese', 'emerging', '{Melodic + Progressive}', 'Switzerland', 'https://www.siamese-records.com/'),
  ('Silky Records', 'silky-records', 'emerging', '{Minimal}', 'UK', 'https://www.silkyrecords.com/'),
  ('Simplexia', 'simplexia', 'emerging', '{House + Techno}', 'Spain', 'https://soundcloud.com/simplexia-records'),
  ('Simulate', 'simulate', 'emerging', '{Melodic + Progressive}', 'UK', 'https://www.simulateofficial.com'),
  ('SINCOPAT', 'sincopat', 'emerging', '{House + Techno}', 'Spain', 'https://www.sincopat.com/'),
  ('Sink or Swim', 'sink-or-swim', 'emerging', '{House + Techno}', 'Netherlands', 'https://soundcloud.com/sinkorswimrecord'),
  ('Sintoniza Records', 'sintoniza-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/sintonizarecords}', NULL, NULL),
  ('SiO', 'sio', 'emerging', '{House}', 'Netherlands', 'https://soundcloud.com/siorecords'),
  ('Siona Records', 'siona-records', 'emerging', '{Melodic + Progressive}', 'Ukraine', 'https://sionarecords.com/'),
  ('Skutta', 'skutta', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/skutta-records}', NULL, NULL),
  ('Slap The Club', 'slap-the-club', 'emerging', '{House}', 'UK', 'https://soundcloud.com/slaptheclub'),
  ('slash', 'slash', 'emerging', '{Trance}', 'Netherlands', 'https://soundcloud.com/slashlabel'),
  ('Snatch! Records', 'snatch-records', 'emerging', '{House}', 'UK', 'https://www.snatchrecords.com/'),
  ('Sneaker Social Club', 'sneaker-social-club', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/sneakersocialclub'),
  ('Solamente', 'solamente', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/solamenteofc'),
  ('Solid Grooves', 'solid-grooves', 'respected', '{House}', 'UK', 'https://www.solidgrooves.co.uk/'),
  ('Solitude MCR', 'solitude-mcr', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/solitude_uk}', NULL, NULL),
  ('Soul Heaven', 'soul-heaven', 'emerging', '{House}', 'UK', 'https://www.soul-heaven.com/'),
  ('Soulfuric', 'soulfuric', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soulfuric-recordings.bandcamp.com/}', NULL, NULL),
  ('Sound D''Elite', 'sound-delite', 'emerging', '{Minimal}', 'Italy', 'https://soundcloud.com/soundelite'),
  ('South of Saturn', 'south-of-saturn', 'emerging', '{Minimal}', 'USA', 'https://www.repopulatemars.com/south-of-saturn'),
  ('Southpoint Records', 'southpoint-records', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/stptmusic}', NULL, NULL),
  ('Space Yacht', 'space-yacht', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://shop.spaceyacht.net/}', NULL, NULL),
  ('Spannung', 'spannung', 'emerging', '{Techno}', 'Germany', 'https://www.instagram.com/spannungrecords/'),
  ('SPECIES', 'species', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://soundcloud.com/species_recs}', NULL, NULL),
  ('Speedmaster Records', 'speedmaster-records', 'emerging', '{}', NULL, NULL),
  ('Trance', 'trance', 'emerging', '{https://soundcloud.com/speedmasterrecords}', NULL, NULL),
  ('Spinnin'' Records', 'spinnin-records', 'emerging', '{House}', 'Netherlands', 'https://spinninrecords.com/'),
  ('Stay On Sight', 'stay-on-sight', 'emerging', '{Techno}', 'UK', 'https://soundcloud.com/skin0nskin'),
  ('Stay True Sounds', 'stay-true-sounds', 'emerging', '{House}', 'South Africa', 'https://staytruesounds.bandcamp.com/'),
  ('Steyoyoke', 'steyoyoke', 'emerging', '{Melodic + Progressive}', 'Germany', 'https://www.steyoyoke.com/'),
  ('STMPD RCRDS', 'stmpd-rcrds', 'emerging', '{EDM}', 'Netherlands', 'https://stmpdrcrds.com/'),
  ('STORIES', 'stories', 'emerging', '{House}', 'UK', 'https://www.thisissarahstory.com/'),
  ('Stress', 'stress', 'emerging', '{House + Techno}', 'UK', 'https://stress-records.com/'),
  ('Strictly Flava', 'strictly-flava', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/strictly-flava}', NULL, NULL),
  ('Strictly Rhythm', 'strictly-rhythm', 'emerging', '{House}', 'USA', 'https://soundcloud.com/strictlyrhythm'),
  ('Sub-Urban Records', 'sub-urban-records', 'emerging', '{House}', 'USA', 'https://sub-urban.bandcamp.com/'),
  ('Subios Records', 'subios-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/subios}', NULL, NULL),
  ('SubVision', 'subvision', 'emerging', '{Techno}', 'Germany', 'https://www.instagram.com/subvisionrecords/'),
  ('SURA Music', 'sura-music', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/suramusiclabel'),
  ('Sushi Muzik', 'sushi-muzik', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.sushimuzik.com/}', NULL, NULL),
  ('Sweat It Out', 'sweat-it-out', 'emerging', '{House}', 'Australia', 'https://sweatitoutmusic.com/'),
  ('Sweatrz Records', 'sweatrz-records', 'emerging', '{Minimal}', 'Australia', 'https://www.instagram.com/sweatrz_records/'),
  ('Synthetic Love Records', 'synthetic-love-records', 'emerging', '{}', NULL, NULL),
  ('Trance', 'trance', 'emerging', '{https://synthetic-love.com/}', NULL, NULL),
  ('Sys.Ex Records', 'sysex-records', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/sysexberlin'),
  ('SYSTEM IPSIPI', 'system-ipsipi', 'emerging', '{Techno}', 'Belarus', 'https://soundcloud.com/system-ipsipi'),
  ('Systolic Records', 'systolic-records', 'emerging', '{Techno}', 'Spain', 'https://soundcloud.com/sys-systolic-recordings'),
  ('T E N E T', 't-e-n-e-t', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.tenetrecordings.com/}', NULL, NULL),
  ('Taapion', 'taapion', 'emerging', '{Techno}', 'France', 'https://taapion.com/'),
  ('TAIPAN TRAX', 'taipan-trax', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/taipantrax'),
  ('Take Notes', 'take-notes', 'emerging', '{Minimal}', 'Romania', 'https://soundcloud.com/takenotesmusic'),
  ('Tamango Records', 'tamango-records', 'emerging', '{Minimal}', 'Italy', 'https://soundcloud.com/tamangorecords'),
  ('Tanzgemeinschaft', 'tanzgemeinschaft', 'emerging', '{Techno}', 'Belgium', 'https://www.tanzgemeinschaft.com/'),
  ('TAU', 'tau', 'emerging', '{Melodic + Progressive}', 'Germany', 'https://www.tautautau.de/'),
  ('Tech Avenue Records', 'tech-avenue-records', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://www.techavenuerecords.com/}', NULL, NULL),
  ('Techaway', 'techaway', 'emerging', '{House}', 'Spain', 'https://soundcloud.com/techawaymusic'),
  ('Techne', 'techne', 'emerging', '{House}', 'UK', 'https://www.noizusound.com/'),
  ('Techords', 'techords', 'emerging', '{Minimal}', 'UK', 'https://soundcloud.com/techordsltd'),
  ('Teewave Records', 'teewave-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/teewave-records}', NULL, NULL),
  ('Teletech', 'teletech', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.teletech.events/}', NULL, NULL),
  ('Terminal M', 'terminal-m', 'emerging', '{Techno}', 'Germany', 'https://terminalm.com/'),
  ('Terminator', 'terminator', 'emerging', '{Techno}', 'USA', 'https://toddterry.com/terminator-records'),
  ('Terms & Conditions Records', 'terms-conditions-records', 'emerging', '{House}', 'Mexico', 'https://soundcloud.com/termsandconditionsrecords'),
  ('TETE VIDE', 'tete-vide', 'emerging', '{}', NULL, NULL),
  ('Trance', 'trance', 'emerging', '{https://soundcloud.com/tetevide-tv}', NULL, NULL),
  ('The Formula', 'the-formula', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://www.instagram.com/theformula_official/}', NULL, NULL),
  ('The Remedy Project', 'the-remedy-project', 'emerging', '{House}', 'UK', 'https://soundcloud.com/theremedyproject'),
  ('The Scripture', 'the-scripture', 'emerging', '{}', NULL, NULL),
  ('Deep', 'deep', 'emerging', '{https://www.instagram.com/wearethescripture/}', NULL, NULL),
  ('The Third Room', 'the-third-room', 'emerging', '{Techno}', 'Germany', 'https://www.thethirdroom.de/'),
  ('The Wub Club', 'the-wub-club', 'emerging', '{UKG}', 'UK', 'https://www.thewubclub.com/'),
  ('theBasement Discos', 'thebasement-discos', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/thebasementmusic}', NULL, NULL),
  ('Things We Never Did', 'things-we-never-did', 'emerging', '{Techno}', 'Belgium', 'https://soundcloud.com/twndmusic'),
  ('This Never Happened', 'this-never-happened', 'emerging', '{Deep}', 'USA', 'https://this-never-happened.com/'),
  ('Three Six Zero', 'three-six-zero', 'emerging', '{House}', 'UK', 'https://www.threesixzero.com/recording'),
  ('THUNDR', 'thundr', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://thundr.co.uk/}', NULL, NULL),
  ('Time Machine', 'time-machine', 'emerging', '{Melodic + Progressive}', 'Italy', 'https://www.instagram.com/timemachineclctv/?hl=en'),
  ('Timeless Moment', 'timeless-moment', 'emerging', '{Melodic + Progressive}', 'Brazil', 'https://soundcloud.com/timelessmoment'),
  ('Tipsy Dreamer', 'tipsy-dreamer', 'emerging', '{Trance}', 'Germany', 'https://soundcloud.com/tipsy-dreamer'),
  ('Tomorrowland Music', 'tomorrowland-music', 'emerging', '{House + Techno}', 'Belgium', 'https://tomorrowlandmusic.com/'),
  ('TOO GOOD tO DIE', 'too-good-to-die', 'emerging', '{Melodic + Progressive}', 'UK', 'https://linktr.ee/tgtd.ofc'),
  ('Too Long Records', 'too-long-records', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/toolongrecords'),
  ('Toolroom Records', 'toolroom-records', 'emerging', '{House}', 'UK', 'https://toolroomrecords.com/'),
  ('TORO', 'toro', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://tororec.co/}', NULL, NULL),
  ('TOTE SONNE', 'tote-sonne', 'emerging', '{Techno}', 'Germany', 'https://totesonne.com/'),
  ('Trace Amounts', 'trace-amounts', 'emerging', '{House}', 'USA', 'https://traceamounts.nyc/'),
  ('Trash Tunes', 'trash-tunes', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/trash-tunes'),
  ('Tribal Pulse', 'tribal-pulse', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/tribal-pulse'),
  ('Trick', 'trick', 'emerging', '{House + Techno}', 'UK', 'https://tricklabel.co.uk/'),
  ('Trippy Ass Technologies', 'trippy-ass-technologies', 'emerging', '{House + Techno}', 'USA', 'https://www.trippyasstechno.com/'),
  ('Trippy Code', 'trippy-code', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.trippycode.com/}', NULL, NULL),
  ('TRONIC', 'tronic', 'emerging', '{Techno}', 'Sweden', 'https://soundcloud.com/tronic-music'),
  ('Truesoul', 'truesoul', 'emerging', '{House + Techno}', 'Sweden', 'https://soundcloud.com/truesoul'),
  ('TXTBK', 'txtbk', 'emerging', '{UKG}', 'UK', 'https://www.txtbk.uk/'),
  ('Tzantza Records', 'tzantza-records', 'emerging', '{}', NULL, NULL),
  ('Minimal', 'minimal', 'emerging', '{https://soundcloud.com/tzantzarecords}', NULL, NULL),
  ('UKF', 'ukf', 'emerging', '{UKG}', 'UK', 'https://ukf.com/'),
  ('Ultra Knites', 'ultra-knites', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{https://soundcloud.com/ultraknitesrecords}', NULL, NULL),
  ('Unbekannt', 'unbekannt', 'emerging', '{Techno}', 'Germany', 'https://www.instagram.com/unbekannt_label/'),
  ('Unity', 'unity', 'emerging', '{House + Techno}', 'Canada', 'https://www.instagram.com/unity_records/'),
  ('UNSEEN', 'unseen', 'emerging', '{Melodic + Progressive}', 'France', 'https://soundcloud.com/unseenrecordings'),
  ('Up the Stuss', 'up-the-stuss', 'emerging', '{Minimal}', 'Netherlands', 'https://www.chrisstussy.com/'),
  ('Upperground', 'upperground', 'emerging', '{Melodic + Progressive}', 'Ukraine', 'https://upperground.art/'),
  ('UИCAGE', 'ucage', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/uncageofficial'),
  ('VERKNIPT', 'verknipt', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.verknipt.org/}', NULL, NULL),
  ('vestige', 'vestige', 'emerging', '{}', NULL, NULL),
  ('Melodic + Progressive', 'melodic-progressive', 'emerging', '{https://soundcloud.com/vestige-records-962700092}', NULL, NULL),
  ('Viceversa', 'viceversa', 'emerging', '{House}', 'Italy', 'https://soundcloud.com/alessioterra'),
  ('Virgo', 'virgo', 'emerging', '{Techno}', 'Germany', 'https://soundcloud.com/virgotransmissions'),
  ('Void+1', 'void1', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/voidplus1recordings'),
  ('Volta Records', 'volta-records', 'emerging', '{Melodic + Progressive}', 'Portugal', 'https://www.volta-records.com/'),
  ('Warehouse Project Records', 'warehouse-project-records', 'emerging', '{House + Techno}', 'UK', 'https://thewarehouseproject.com/whp-records/'),
  ('WarinD Records', 'warind-records', 'emerging', '{Techno}', 'Italy', 'https://soundcloud.com/warind'),
  ('Warm Up Recordings', 'warm-up-recordings', 'emerging', '{Techno}', 'Spain', 'https://soundcloud.com/oscarmulero'),
  ('Watergate Records', 'watergate-records', 'emerging', '{Melodic + Progressive}', 'Germany', 'https://soundcloud.com/watergaterecords'),
  ('WEIRD STUFF Records', 'weird-stuff-records', 'emerging', '{Minimal}', 'Italy', 'https://weirdstuffmusic.com/'),
  ('Well Street Records', 'well-street-records', 'emerging', '{}', NULL, NULL),
  ('UKG', 'ukg', 'emerging', '{https://soundcloud.com/wellstreet}', NULL, NULL),
  ('Whalien', 'whalien', 'emerging', '{Techno}', 'Germany', 'https://www.whalien-berlin.com/'),
  ('When Stars Align', 'when-stars-align', 'emerging', '{Melodic + Progressive}', 'UK', 'https://whenstarsalign.komi.io/'),
  ('Whoyostro', 'whoyostro', 'emerging', '{House}', 'Ukraine', 'https://soundcloud.com/whoyostro'),
  ('Whoyostro White', 'whoyostro-white', 'emerging', '{Deep}', 'Ukraine', 'https://soundcloud.com/whoyostrow'),
  ('widerworks', 'widerworks', 'emerging', '{Melodic + Progressive}', 'Turkey', 'https://widerbergmusic.com/'),
  ('Witty Tunes', 'witty-tunes', 'emerging', '{}', NULL, NULL),
  ('House', 'house', 'emerging', '{http://wittytunes.com/}', NULL, NULL),
  ('Yes Yes Yes', 'yes-yes-yes', 'emerging', '{House}', 'USA', 'https://www.instagram.com/yesyesyespresents/?hl=en'),
  ('yesmatewotusaying', 'yesmatewotusaying', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/yesmatewotusayin'),
  ('Yosh Bass', 'yosh-bass', 'emerging', '{UKG}', 'UK', 'https://soundcloud.com/yoshbass'),
  ('Zamna Records', 'zamna-records', 'emerging', '{Melodic + Progressive}', 'Mexico', 'https://zmaagency.com/talents/zamna-records/'),
  ('ZEF Music', 'zef-music', 'emerging', '{}', NULL, NULL),
  ('House + Techno', 'house-techno', 'emerging', '{https://soundcloud.com/zefclub}', NULL, NULL),
  ('Vault Records', 'vault-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.vault-sessions.com/}', NULL, NULL),
  ('HATE Collective', 'hate-collective', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/hate_music}', NULL, NULL),
  ('Bassiani', 'bassiani', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://bassiani.com/light/label}', NULL, NULL),
  ('Fuse Imprint', 'fuse-imprint', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://www.fuse.be/}', NULL, NULL),
  ('Laster', 'laster', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/lasterclub}', NULL, NULL),
  ('Tresor Records', 'tresor-records', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://tresorberlin.com/}', NULL, NULL),
  ('Synergie', 'synergie', 'emerging', '{}', NULL, NULL),
  ('Techno', 'techno', 'emerging', '{https://soundcloud.com/kollektivsynergie}', NULL, NULL)
ON CONFLICT (slug) DO NOTHING;